# Generated by Django 5.1.7 on 2025-04-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_alter_attempttosend_options_alter_mailing_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=50, verbose_name="Почта"),
        ),
    ]
